### ISSUE TITLE
404 for http://www.deadliners.net/68000Reasons/js/3rdParty/jquery-1.11.2.min.js

### ISSUE THREAD

**Issue by valioDOTch** [fcondolo/68000Reasons#1]
On your deployment on http://www.deadliners.net/68000Reasons the jQuery file seems to have gone missing.

Suggestion: reupload or use a CDN for jQuery 1.11.2 http://jquery.com/download/

**Comment by fcondolo** [comment]
Hello Pat,

Issue fixed. Thanks a lot for the heads up!

Cheers,
Frederic.

2015-09-25 20:33 GMT+02:00 Pat Mächler notifications@github.com:

**Comment by valioDOTch** [comment]
:+1:
